[build]
  publish = "."

[[redirects]]
  from = "/pemesanan"
  to = "/pemesanan.html"
  status = 200

[[redirects]]
  from = "/booking"
  to = "/pemesanan.html"
  status = 301

[[redirects]]
  from = "/riwayat"
  to = "/riwayat.html"
  status = 200

[[redirects]]
  from = "/history"
  to = "/riwayat.html"
  status = 301

[[redirects]]
  from = "/dasbor"
  to = "/dasbor-admin.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/dasbor-admin.html"
  status = 301

[[redirects]]
  from = "/admin.html"
  to = "/dasbor-admin.html"
  status = 301
