[build]
  publish = "."

[[redirects]]
  from = "/booking"
  to = "/booking.html"
  status = 200

[[redirects]]
  from = "/pemesanan"
  to = "/booking.html"
  status = 200

[[redirects]]
  from = "/history"
  to = "/history.html"
  status = 200

[[redirects]]
  from = "/riwayat"
  to = "/history.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/dasbor-admin"
  to = "/admin.html"
  status = 200
